### ISSUE TITLE
Source code of firmware

### ISSUE THREAD

**Issue by groessler** [robinhedwards/A8PicoCart#12]
Hi,

is the source code of the firmware (a8_pico_cart.uf2) available somewhere?

best regards,
chris

**Comment by kneehighspy** [comment]
yes,A8PicoCart/firmware at main · robinhedwards/A8PicoCartgithub.comthanks!On Feb 2, 2024, at 2:50 PM, Christian Groessler ***@***.***> wrote:﻿
Hi,
is the source code of the firmware (a8_pico_cart.uf2) available somewhere?
best regards,
chris

**Comment by groessler** [comment]
Sorry, there's no source code. Just a binary.

**Comment by kneehighspy** [comment]
A8PicoCart/source at main · robinhedwards/A8PicoCartgithub.comthanks!On Feb 2, 2024, at 3:50 PM, Christian Groessler ***@***.***> wrote:﻿
Sorry, there's no source code. Just a binary.

**Comment by groessler** [comment]
Hmm. Stupid me. Sure there is in "source/Pico VSCode Project/a8_pico_cart/"...

**Comment by groessler** [comment]
PEBKAC error...
