### ISSUE TITLE
remixed cartridge shell 3d print files

### ISSUE THREAD

**Issue by VonHirsch** [robinhedwards/A8PicoCart#3]
I created and uploaded a cartridge shell remix on Thingverse, letting you know in case you think it's worth linking to.  Thanks for this project!!

https://www.thingiverse.com/thing:6257150

Changes:

Moved reset hole .5 mm towards inside
Increased the diameter of the M3 screw through hole (a8pico_front)
Modified the bottom to take knurled brass threaded heat set inserts
Removed problematic gap between through-hole and thread entry

**Comment by robinhedwards** [comment]
thanks!
